language: go
go:
 - 1.13.x
 - 1.14.x
arch:
 - amd64
 - arm64
env:
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libatlas-base-dev
 - cd /tmp && wget https://github.com/cjlin1/liblinear/archive/v241.tar.gz && tar xvf v241.tar.gz && cd liblinear-241 && make lib && sudo install -vm644 linear.h /usr/include && sudo install -vm755 liblinear.so.4 /usr/lib && sudo ln -sfv liblinear.so.4 /usr/lib/liblinear.so
 - cd $TRAVIS_BUILD_DIR
install:
 - go get github.com/smartystreets/goconvey/convey
 - go get -v ./...

script:
 - ./coverage.sh

after_success:
 - bash <(curl -s https://codecov.io/bash)
